management:
  endpoints:
    web:
      exposure:
        include: bindings # enable the bindings actuator endpoints

spring:
  cloud:
    stream:
      output-bindings: toStream # Create explicitly a binding. No need to create a spring cloud function.
      function:
        autodetect: false # Disable auto-discovery of beans to bind to external destination(s) exposed by the bindings (see https://docs.spring.io/spring-cloud-stream/reference/spring-cloud-stream/producing-and-consuming-messages.html#overview Notes)

    function:
      definition: uppercase; reverse; uppercase|reverse # Specifies beans to bind to external destinations. The pipe let you combine multiple function.
      bindings:
        uppercase|reverse-in-0: uppercaseAndReverseInput # binding a name. This new name can be used in configurations instead of the original once.
        uppercase|reverse-out-0: uppercaseAndReverseOutput